# This is a basic workflow to help you get started with Actions

name: Auto Close PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, reopened]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  auto-close:
    runs-on: ubuntu-latest
    steps: 
      - name: Check if PR is from a spcific user
        id: check_user
        run: |
          if [ "${{ gihub.actor }}" = "3rr0r4x4" ]: 
          then 
            echo "Matched the user"
            echo "::set-output name=should_clos::true"
          else 
            echo "Did not match the user"
            echo "::set-output name=should_close:false"
          fi
      - name: Close PR
        if: steps.check_user.out-puts.should_close == 'true'
        uses: peter-evans/close-pull@v1
        with: 
          comment: "Auto-closing pull request from designated user"
